### ISSUE TITLE
Misalignment on Cost boxes on Advanced tab (Firefox)

### ISSUE THREAD

**Issue by r-valyar** [Perfectro/wrath-and-glory-foundry-vtt#2]
On Firefox there is misalignment on the cost boxes in Advanced tab. 
![image](https://user-images.githubusercontent.com/63558984/100581463-6ef4aa00-32f0-11eb-8936-5b23e495bec1.png)

**Comment by Perfectro** [comment]
Firefox isn't supported. You should use a chromium based browser.

**Comment by r-valyar** [comment]
Sorry, what isn't supported means? Is not supported by what?

**Comment by Perfectro** [comment]
By this system. I don't test it on firefox so stuff like this will happen.
The sheet is design with chromium based browser in mind.

**Comment by r-valyar** [comment]
Do you plan to bring FF on board? The FF browser and font rendering engine is much more crisp and readable with serif fonts compared to Chrome/MS Edge (chromium) and all players are using it because of this. 

Chromium have this blurr that makes things not nice with fine print. I can show side by side comparison and it is quite obvious. :)

**Comment by Perfectro** [comment]
No I don't.
If you want to make a PR for it, be my guest.
