### ISSUE TITLE
"Post Item" of Weapon category in chat has missing info

### ISSUE THREAD

**Issue by r-valyar** [Perfectro/wrath-and-glory-foundry-vtt#4]
When we post item to chat, the Damage/AP/ED is [object Object]. Not sure if this is bug or something I haven't populated properly. Adding screenshot with the item profile and chat output. 
![image](https://user-images.githubusercontent.com/63558984/100631629-98372980-3334-11eb-9e44-5f3cf207cdc5.png)

**Comment by Perfectro** [comment]
Fixed on [1.7.0](https://github.com/Perfectro/wrath-and-glory-foundry-vtt/releases/tag/v1.7)

**Comment by r-valyar** [comment]
Wow, thanks, super prompt!
