### ISSUE TITLE
Unable to roll Influence

### ISSUE THREAD

**Issue by r-valyar** [Perfectro/wrath-and-glory-foundry-vtt#5]
The Influence button in Gear tab is being highlighted as active button but no roll dialog box appears. How influence is done?

**Comment by Perfectro** [comment]
That was a bug.
Fixed on [1.8.0](https://github.com/Perfectro/wrath-and-glory-foundry-vtt/releases/tag/v1.8)

**Comment by r-valyar** [comment]
Thank you!
